### ISSUE TITLE
Error with openjdk 11.0.8

### ISSUE THREAD

**Issue by vicenrico** [EclipseNebula/nebula#273]
Added only this line after the main view creation: 
	
`Dialog.inform("Loading", "Test");`

This is the error:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.eclipse.nebula.widgets.opal.commons.SWTGraphicUtil.addDisposer(org.eclipse.swt.widgets.Widget, org.eclipse.swt.graphics.Resource)'
	at org.eclipse.nebula.widgets.opal.dialog.DialogArea.getTitleColor(DialogArea.java:105)
	at org.eclipse.nebula.widgets.opal.dialog.MessageArea.createTitle(MessageArea.java:286)
	at org.eclipse.nebula.widgets.opal.dialog.MessageArea.render(MessageArea.java:219)
	at org.eclipse.nebula.widgets.opal.dialog.Dialog.show(Dialog.java:111)
	at org.eclipse.nebula.widgets.opal.dialog.Dialog.inform(Dialog.java:297)
	at org.eclipse.nebula.widgets.opal.dialog.Dialog.inform(Dialog.java:286)
	at net.VisualDivX.Controller.Controller.<init>(Controller.java:30)

I've only created the main Display and Shell. Afterwards, I get this error message. With java 8 was working fine, but I need java 11. 
My java version is  AdoptOpenJDK 11.0.8. Have you tested with java 8+ and above?
```

**Comment by wimjongman** [comment]
It looks like you are using an older version of opal commons. Please update to the latest Nebula. If the issues persists please add a snippet that reproduces the issue.

**Comment by lcaron** [comment]
Hi
I just tried the dialog snippets with JDK 13 without problem. Can you try with a recent release and give us more information ?

**Comment by vicenrico** [comment]
Sorry for the delay. As wimjongman suggested, I was using an older version of opal commons. I don't know why, because I though it was the last version, but it wasn't. Now it's working fine, thanks!!!
