### ISSUE TITLE
Widget org.eclipse.nebula.widgets.passwordrevealer.PasswordRevealer is not supported for Eclipse databinding

### ISSUE THREAD

**Issue by videgro** [EclipseNebula/nebula#299]
**Trying to bind the PasswordRevealer to a data model will result in a 'not supported' error.**

### Example code

```
import org.eclipse.core.databinding.Binding;
import org.eclipse.core.databinding.beans.typed.BeanProperties;
import org.eclipse.core.databinding.observable.value.IObservableValue;
import org.eclipse.jface.databinding.swt.typed.WidgetProperties;
import org.eclipse.nebula.widgets.passwordrevealer.PasswordRevealer;

final PasswordRevealer revealer = new PasswordRevealer(shell, SWT.NONE);

final IObservableValue<Object> passwordModel = BeanProperties.value(CredentialModel.class,CredentialModel.PROP_PASSWORD).observe(model.getUser());
final IObservableValue<String> targetPassword = WidgetProperties.text(SWT.Modify).observe(revealer);

new DataBindingContext().bindValue(targetPassword, passwordModel);
```

### Will result in error

```
java.lang.NoSuchMethodException: org.eclipse.nebula.widgets.passwordrevealer.PasswordRevealer.addPropertyChangeListener(java.beans.PropertyChangeListener)
         at java.lang.Class.getMethod(Class.java:1786)
         ... 

 
Widget [org.eclipse.nebula.widgets.passwordrevealer.PasswordRevealer] is not supported.
         at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
         at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
         at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
         at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
         at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
         at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
         at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
         at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
         at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4213)
         at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
         at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4030)
         at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3630)
         at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
         at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
         at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
         at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
         at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:166)
         at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
         at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
         at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
         at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
         at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:498)
         at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
         at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
         at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
         at org.eclipse.equinox.launcher.Main.main(Main.java:1420)

Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.IllegalArgumentException: Widget [org.eclipse.nebula.widgets.passwordrevealer.PasswordRevealer] is not supported.
         at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
         at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
         at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
         at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
         at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
         ... 29 more

Caused by: java.lang.IllegalArgumentException: Widget [org.eclipse.nebula.widgets.passwordrevealer.PasswordRevealer] is not supported.
```

### Solution
1) Please make this widget compatible to bind like a normal Text widget OR
2) Give directions/example code how to create a data binding between this widget and a data model

**Comment by wimjongman** [comment]
Hey @videgro, thanks for the report. The widget is not a Text but a Composite. You have to define it differently in data-binding. Please invest some time finding out how to bind something else but a text.

You have to use another strategy instead of WidgetProperties.text, maybe you can use beanproperty or else pojoproperty.

Let us know how you finally did it.

**Comment by wimjongman** [comment]
ping @videgro

**Comment by lcaron** [comment]
Any news @videgro about this issue ?

**Comment by lcaron** [comment]
Any news @videgro about this issue ?

**Comment by lcaron** [comment]
@videgro this issue did not move since about 6 month, so I prefer to close it. Feel free to reopen if you think this is relevant
