### ISSUE TITLE
[RichText][Webkit] Canont load the rich text editor

### ISSUE THREAD

**Issue by rbioteau** [EclipseNebula/nebula#360]
It looks like there are asynchronous issues when the rich text editor tries to load itself.
I use a custom configuration. Like this:

```java
      RichTextEditorConfiguration richTextEditorConfiguration = new RichTextEditorConfiguration();
        richTextEditorConfiguration.setToolbarCollapsible(true);
        richTextEditorConfiguration.setRemovePasteFromWord(true);
        richTextEditorConfiguration.setRemovePasteText(true);
        richTextEditorConfiguration.setRemoveFormat(false);
        richTextEditorConfiguration.setToolbarInitialExpanded(true);
        richTextEditorConfiguration.setOption(RichTextEditorConfiguration.REMOVE_PLUGINS, "elementspath,flash");
        richTextEditorConfiguration.setOption(RichTextEditorConfiguration.TOOLBAR_GROUPS, "["
                + "{ name: 'styles' },"
                + "{ name: 'basicstyles', groups: [ 'basicstyles','colors', 'cleanup' ] },"
                + "{ name: 'paragraph', groups: [ 'list', 'indent', 'align' ] },"
                + "{ name: 'links' },"
                + "{ name: 'other' },"
                + "{ name: 'insert' }"
                + "]");
        List<String> hiddenButtons = new ArrayList<>();
        if (Platform.OS_MACOSX.equals(Platform.getOS())) {
            hiddenButtons.add("TextColor");
            hiddenButtons.add("BGColor");
            hiddenButtons.add("Styles");
            hiddenButtons.add("Font");
            hiddenButtons.add("FontSize");
        }
        hiddenButtons.add("Flash");
        hiddenButtons.add("PageBreak");
        hiddenButtons.add("Iframe");
        hiddenButtons.add("Smiley");
        hiddenButtons.add("Subscript");
        hiddenButtons.add("Anchor");
```

I get the following stack when the `initEditor()` is invoked by the browser

```
org.eclipse.swt.SWTException: file:///path/to/rcp/plugins/org.eclipse.nebula.widgets.richtext_1.3.0.202007241204/org/eclipse/nebula/widgets/richtext/resources/template.html:213:50: ReferenceError: Can't find variable: getAllOptions
Script that was evaluated:
function SWTWebkit2TempFunc38(){initEditor();}; SWTWebkit2TempFunc38()
at org.eclipse.swt.browser.WebKit$Webkit2AsyncToSync.runjavascript(WebKit.java:1184)
at org.eclipse.swt.browser.WebKit$Webkit2AsyncToSync.evaluate(WebKit.java:1127)
at org.eclipse.swt.browser.WebKit.evaluate(WebKit.java:1445)
at org.eclipse.swt.browser.WebBrowser.evaluate(WebBrowser.java:406)
at org.eclipse.swt.browser.Browser.evaluate(Browser.java:670)
at org.eclipse.swt.browser.Browser.evaluate(Browser.java:619)
at org.eclipse.nebula.widgets.richtext.RichTextEditor$3.completed(RichTextEditor.java:285)
at org.eclipse.swt.browser.WebKit.lambda$7(WebKit.java:1911)
```

It works properly on Windows.

GTK versions
```
org.eclipse.swt.internal.deviceZoom=200
org.eclipse.swt.internal.gdk.backend=x11
org.eclipse.swt.internal.gtk.theme=Yaru
org.eclipse.swt.internal.gtk.version=3.24.20
org.eclipse.swt.internal.webkitgtk.version=2.32.3
```

System package version
```
libwebkit2gtk-4.0-37/focal-updates,focal-security,now 2.32.3-0ubuntu0.20.04.1 amd64
```

Thanks for your help.

**Comment by lcaron** [comment]
Bonjour Romain

Mmmmm it seems to be an SWT error. Which version of SWT do you use ?

Regards

Laurent

Le jeu. 12 août 2021 à 13:13, Romain Bioteau ***@***.***> a
écrit :

**Comment by rbioteau** [comment]
Hi Laurent,
It seems that the culprit is `libwebkit2gtk-4.0-37`. After a revert to an older version (`2.28.1-1` instead of `2.32.3-0ubuntu0.20.04.1`) the issue is gone.

I managed to reproduce the issue using the `RichTextEditorExample` and disposing an editor instance like this:

```java

	public void createControls(Composite parent) {
		parent.setLayout(new GridLayout(1, true));

		RichTextEditor aeditor = new RichTextEditor(parent);
		GridDataFactory.fillDefaults().grab(true, true).applyTo(aeditor);
                
		aeditor.dispose();

		RichTextEditor editor = new RichTextEditor(parent);
		GridDataFactory.fillDefaults().grab(true, true).applyTo(editor);

		final Text htmlOutput = new Text(parent,
				SWT.MULTI | SWT.BORDER | SWT.WRAP | SWT.V_SCROLL | SWT.READ_ONLY);
		GridDataFactory.fillDefaults().grab(true, false).hint(SWT.DEFAULT, 100).applyTo(htmlOutput);

		editor.addModifyListener(new ModifyListener() {

			@Override
			public void modifyText(ModifyEvent e) {
				htmlOutput.setText(editor.getText());
			}
		});

		editor.addKeyListener(new KeyAdapter() {

			@Override
			public void keyPressed(KeyEvent e) {
				System.out.println("keycode: " + e.keyCode);
				System.out.println("character: " + e.character);
			}
		});

		editor.addToolbarButton(new ToolbarButton("jsButton",
				"myScriptCommand", "Execute Javascript", "other,0",
				RichTextEditorExample.class.getResource("images/environment_co.gif")) {
			@Override
			public String getJavascriptToExecute() {
				return "alert('Javascript call')";
			}
		});

		// add additional controls for showing interactions
		createControlPanel(parent, editor);

	}
```

This fails in `2.32.3` not `2.28.1`.

I don't know what can be done on Nebula side to avoid this.

Thanks for your help.

**Comment by laeubi** [comment]
AFAIK GTK2 is no longer supported by SWT, you should probably update to a more recent version that uses GTK3

**Comment by rbioteau** [comment]
I'm using GTK3. It is the webkitgtk lib that is the issue here.

**Comment by lcaron** [comment]
I do not think that something can be done on Nebula.
Maybe you should get in touch with the SWT Team ?

**Comment by rbioteau** [comment]
I have filled an issue on the [eclipse bugzilla](https://bugs.eclipse.org/bugs/show_bug.cgi?id=575472)

:crossed_fingers:

**Comment by lcaron** [comment]
Hi Romain,

Well, it seems that we are neighbours (I live & work in Lyon :) )

I propose to close this issue and reopen it if the SWT Team asks an help or a modification in the Nebula code. 
Are you ok with that ?

**Comment by rbioteau** [comment]
We actually already met each other in Grenoble  😉
I'm ok to close the issue here. It seems that the SWT ticket got some attention so it is on good track to be addressed.
Thanks !

**Comment by cpfeiffer** [comment]
For reference, this [is fixed](https://bugs.eclipse.org/bugs/show_bug.cgi?id=575472) with eclipse 4.24.

**Comment by lcaron** [comment]
Thank you for this feedback
