### ISSUE TITLE
Image not disposed in PWTabContainer

### ISSUE THREAD

**Issue by vogella** [EclipseNebula/nebula#362]
During shutdown Eclipse reports that an image was not dispose.

Tbw. the code looks ok to me, line 117 adds a dispose listener, not sure what is wrong here.

java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:205)
	at org.eclipse.nebula.widgets.opal.preferencewindow.PWTabContainer.lambda$0(PWTabContainer.java:104)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1067)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1048)
	at org.eclipse.swt.widgets.Control.WM_SIZE(Control.java:5462)
	at org.eclipse.swt.widgets.Scrollable.WM_SIZE(Scrollable.java:360)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1718)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4837)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4930)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:91)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5692)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4850)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4938)
	at org.eclipse.swt.internal.win32.OS.EndDeferWindowPos(Native Method)
	at org.eclipse.swt.widgets.Composite.resizeChildren(Composite.java:986)
	at org.eclipse.swt.widgets.Composite.resizeChildren(Composite.java:963)
	at org.eclipse.swt.widgets.Composite.setResizeChildren(Composite.java:1159)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1733)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4837)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4930)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:91)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5692)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4850)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4938)
	at org.eclipse.swt.internal.win32.OS.EndDeferWindowPos(Native Method)
	at org.eclipse.swt.widgets.Composite.resizeChildren(Composite.java:986)
	at org.eclipse.swt.widgets.Composite.resizeChildren(Composite.java:963)
	at org.eclipse.swt.widgets.Composite.setResizeChildren(Composite.java:1159)
	at org.eclipse.swt.widgets.Composite.sendResize(Composite.java:1017)
	at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1060)
	at org.eclipse.swt.widgets.Decorations.setBoundsInPixels(Decorations.java:798)
	at org.eclipse.swt.widgets.Shell.setBoundsInPixels(Shell.java:1561)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3233)
	at org.eclipse.swt.widgets.Control.setSizeInPixels(Control.java:3774)
	at org.eclipse.swt.widgets.Control.setSize(Control.java:3804)
	at org.eclipse.swt.widgets.Control.pack(Control.java:2212)
	at org.eclipse.swt.widgets.Control.pack(Control.java:2182)
	at org.eclipse.nebula.widgets.opal.preferencewindow.PreferenceWindow.openShell(PreferenceWindow.java:212)
	at org.eclipse.nebula.widgets.opal.preferencewindow.PreferenceWindow.open(PreferenceWindow.java:157)
	at aero.minova.rcp.preferencewindow.pages.ApplicationPreferenceWindowHandler.execute(ApplicationPreferenceWindowHandler.java:139)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:195)
	at aero.minova.rcp.uitests.MenuTest.lambda$0(MenuTest.java:67)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4001)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:168)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:53)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:48)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1435)

**Comment by laeubi** [comment]
>  the code looks ok to me, line 117 adds a dispose listener, not sure what is wrong here

The problem is that `SWTGraphicUtil.addDisposer(buttonContainer, oldButtonContainerImage); `will only work if the image never changes but it is reasiggned in line 115

As it is likely null at the time of calling `SWTGraphicUtil.addDisposer` it will never dispose anything. I think a new method would be required here instead

```
public static void addDisposer(final Widget widget, final Supplier<Resource> dynamic) {
widget.addDisposeListener(e -> {
                      resource = dynamic.get()
	if (resource == null) {
		return;
	}
	safeDispose(resource);
});
}
```

**Comment by vogella** [comment]
cc @lcaron

**Comment by lcaron** [comment]
Hi

 I am on holidays for the moment, I'll have a look next week.

Cheers

Laurent

Le mer. 18 août 2021 à 14:46, Lars Vogel ***@***.***> a
écrit :

**Comment by vogella** [comment]
Thanks

Laurent CARON ***@***.***> schrieb am Di., 31. Aug. 2021,
10:58:
