### ISSUE TITLE
PWTabContainer.java:104 java.lang.Error: SWT Resource was not properly disposed

### ISSUE THREAD

**Issue by vogella** [EclipseNebula/nebula#373]
We see  swt resource not properly disposed exception in our RCP client.

Maybe you can use a LocalResourceManager?

java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:205)
	at org.eclipse.nebula.widgets.opal.preferencewindow.PWTabContainer.lambda$0(PWTabContainer.java:104)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4237)

**Comment by lcaron** [comment]
Bug fixed in Nebula 2.6.0

**Comment by vogella** [comment]
Thank you, Laurent

Laurent CARON ***@***.***> schrieb am Do., 21. Okt. 2021,
22:10:
