### ISSUE TITLE
Dialog Error (Eclipse 2022-09)

### ISSUE THREAD

**Issue by rcpsync** [EclipseNebula/nebula#494]
An error occurs in the Eclipse 2022-09

Dailog package

Occurs when the OK, Cancel ...  button is pressed.

The same is error when using ChoiceItem
------------------------------------------------------------------------------
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
	at org.eclipse.swt.widgets.Button.getSelection(Button.java:623)
	at org.eclipse.e4.ui.css.swt.dom.ButtonElement$1.widgetSelected(ButtonElement.java:37)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)

**Comment by rcpsync** [comment]
I solved.

below code changed in FooterArea class

FooterArea.this.parent.shell.dispose();
to
Display.getDefault().asyncExec(new Runnable() {
                    FooterArea.this.parent.shell.dispose();
}

**Comment by rcpsync** [comment]
not solved.....

**Comment by rcpsync** [comment]
not solved
